version: 2

models:
  - name: int_clientes__colaboradores_agencias
    description: >
      Modelo intermediário que consolida informações de clientes, colaboradores e agências.
      Permite análises cruzadas por perfil de cliente, responsável comercial e localização da agência.

    columns:
      - name: cod_colaborador
        description: Identificador único do colaborador.

      - name: primeiro_nome_colaborador
        description: Primeiro nome do colaborador, formatado com capitalização adequada.

      - name: ultimo_nome_colaborador
        description: Último nome do colaborador, formatado com capitalização adequada.

      - name: cpf_colaborador
        description: CPF do colaborador, limpo e sem pontuação.

      - name: cod_agencia
        description: Identificador único da agência vinculada ao colaborador.

      - name: nome_agencia
        description: Nome da agência bancária.

      - name: cidade_agencia
        description: Cidade onde a agência está localizada.

      - name: uf_agencia
        description: Unidade federativa (UF) da agência.

      - name: cod_cliente
        description: Identificador único do cliente.

      - name: primeiro_nome_cliente
        description: Primeiro nome do cliente, formatado com capitalização adequada.

      - name: ultimo_nome_cliente
        description: Último nome do cliente, formatado com capitalização adequada.

      - name: cpf_cliente
        description: CPF ou CNPJ do cliente

