name: 'banco_banvic'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  banco_banvic:
    +materialized: view  # padrão para todos os modelos
    staging:
      +schema: staging
      erp:
        +schema: erp
    intermediate:
      +schema: int
      +materialized: table
    marts:
      +schema: marts
      +materialized: table